#name: Secrets example
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Test
        run: |
          echo $API_KEY
        env:
          SERVICE_API: ${{ secrets.SERVICE_API }}
          API_KEY: ${{ secrets.API_KEY }}
